import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export default function Home({ onStart, connecting, connectionError, onViewHistory, onAdmin, theme = 'dark', onToggleTheme }) {
    const [name, setName] = useState('');
    function handleSubmit(e) {
        e.preventDefault();
        if (name.trim() && !connecting) {
            onStart(name.trim());
        }
    }
    return (_jsxs("div", { className: "min-h-screen flex flex-col items-center justify-center px-4 relative overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-cover bg-center bg-no-repeat", style: { backgroundImage: "url('/moniepoint-bg.png')" } }), _jsx("div", { className: "absolute inset-0 bg-[#0d1117]/80" }), _jsx("div", { className: "absolute inset-0 -z-10", style: {
                    background: 'radial-gradient(ellipse at 50% 40%, #0e1a2e 0%, #0d1117 70%)',
                } }), _jsxs("div", { className: "relative z-10 flex flex-col items-center w-full", children: [_jsxs("div", { className: "text-center mb-10", children: [_jsx("div", { className: "text-[#3fb950] text-xs tracking-widest uppercase mb-3 font-mono", children: "\u25CF SYSTEM READY" }), _jsx("h1", { className: "text-4xl font-bold text-[#e6edf3] font-mono mb-3 tracking-tight", children: "Moniepoint SRE Simulation Platform" }), _jsx("p", { className: "text-[#8b949e] text-sm font-mono whitespace-nowrap", children: "Real incidents. Real pressure. Validate your on-call readiness." })] }), _jsx("div", { className: "w-full max-w-sm bg-[#161b22]/95 backdrop-blur border border-[#30363d] rounded-lg p-6 space-y-5", children: _jsxs("form", { onSubmit: handleSubmit, className: "space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs text-[#8b949e] uppercase tracking-widest mb-2 font-mono", children: "Your Name" }), _jsx("input", { type: "text", value: name, onChange: e => setName(e.target.value), placeholder: "e.g. Jane Smith", className: "w-full bg-[#0d1117] border border-[#30363d] rounded px-3 py-2 text-sm font-mono text-[#e6edf3] placeholder-[#484f58] focus:outline-none focus:border-[#3fb950] transition-colors", disabled: connecting, autoFocus: true }), _jsx("p", { className: "text-[#484f58] text-xs font-mono mt-1.5", children: "Enter the name your assessor registered you under." })] }), connectionError && (_jsxs("div", { className: "p-3 bg-[#0d1117] border border-[#f85149] rounded text-xs font-mono text-[#f85149]", children: ["\u2717 ", connectionError] })), _jsx("button", { type: "submit", disabled: !name.trim() || connecting, className: "w-full bg-[#238636] hover:bg-[#2ea043] disabled:bg-[#161b22] disabled:text-[#484f58] disabled:border-[#30363d] text-[#e6edf3] font-mono font-bold py-3 px-4 rounded border border-[#2ea043] disabled:border-[#30363d] transition-all text-sm tracking-wide", children: connecting ? '◉ CONNECTING...' : '▶ START SIMULATION' })] }) }), _jsxs("div", { className: "mt-6 flex items-center gap-6 text-xs font-mono text-[#484f58]", children: [_jsx("button", { onClick: onViewHistory, className: "hover:text-[#58a6ff] transition-colors", children: "\uD83D\uDCCB Session History" }), _jsx("span", { children: "\u00B7" }), _jsx("button", { onClick: onAdmin, className: "hover:text-[#8b949e] transition-colors", children: "Admin" }), _jsx("span", { children: "\u00B7" }), _jsx("button", { onClick: onToggleTheme, className: "hover:text-[#8b949e] transition-colors", title: `Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`, children: theme === 'dark' ? '☀ Light' : '◑ Dark' })] })] })] }));
}
